### ISSUE TITLE
The installed module is not the latest code

### ISSUE THREAD

**Issue by afiorenza** [I-Gave/meta-auth#1]
Hi, 
  First of all, great library! But i have an issue that with `npm install meta-auth` i get the version 1.1.0 which seems to be the latest release. But when i try to use it i receive an error:
```
uncaught TypeError: res.forEach is not a function
    at Object.$.get [as success] ((index):34)
    at i (jquery-2.2.4.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-2.2.4.min.js:2)
    at z (jquery-2.2.4.min.js:4)
    at XMLHttpRequest.<anonymous> (jquery-2.2.4.min.js:4)
```
Checking the node_modules the index.js is not the same as https://github.com/I-Gave/meta-auth/blob/master/index.js so it seems there is a release missing. If i replace the index.js for the latest code it is working fine.

Thanks,
  Agustín.

**Comment by tenthirtyone** [comment]
Thanks for catching this.
